version: '3.1'

services:
  db:
    container_name: tcc_db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: tcc
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: 684d9a84a8
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - tcclocal
  nginx:
    container_name: tcc_nginx
    image: nginx:stable-alpine
    depends_on:
      - db
    ports:
      - "80:80"
      - "443:443"
    volumes: &appvolumes
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html:cached
      -  phpmyadmin_data:/var/www/phpmyadmin
#      - ./nginx/error.log:/logs/error.log
      -  phpmyadminconf:/etc/phpmyadmin
      - ./env/php.ini:/usr/local/etc/php/php.ini
      - ./env/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    networks:
      - tcclocal
  php:
    image: php:8.1-fpm
    container_name: tcc_php
    volumes: *appvolumes
    depends_on:
      - db
    build:
      context: .
      dockerfile: php.dockerfile
    networks:
      - tcclocal

  phpmyadmin:
    container_name: tcc_phpmyadmin
    image: phpmyadmin:fpm-alpine
    restart: always
    ports:
      - "8888:80"
    depends_on:
      - db
    environment:
      UPLOAD_LIMIT: 256M
      MYSQL_ROOT_PASSWORD: 684d9a84a8
      PMA_HOST: db
    volumes:
      - /sessions
      - phpmyadmin_data:/var/www/html
      - phpmyadminconf:/etc/phpmyadmin

  mailcatcher:
    container_name: tcc_mailcatcher
    restart: on-failure:10
    links:
      - php
      - nginx
    image: stpaquet/alpinemailcatcher:latest # or any other image you want to use
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - tcclocal

networks:
  tcclocal:
volumes:
  dbdata:
  phpmyadmin_data:
  phpmyadminconf:
